import React from "react";
import Head from "next/head";

import AboutComponent from "@/components/about";

export default function Home() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AboutComponent />
    </>
  );
}
